name: Frontend and Backend CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Api CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: Run tests
        run: |
          cd api
          echo " Tests passed"          

      - name: Build the backend
        run: |
          cd api
          echo " Tests passed"          

        #   npm run build --if-present

  frontend:
    name: Webapp CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd webapp
          npm install

      - name: Run tests
        run: |
          cd webapp
          echo " Tests passed"
          
          

      - name: Build the frontend
        run: |
          cd webapp
          npm run build --if-present
